<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class tecno extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tecnologias')->insert([
            [
                'nombre' => 'laptop',
                'marca' => 'lenovo',
                'serie' => 'Origen - DINID',
                'lugar' => 'Oficina de comunicaciones',
                'estado' => 'En funcionamiento',
                'personal_id' => 7,
                'created_at' => '2026-05-22 13:12:45',
                'updated_at' => '2026-07-15 11:31:01',
            ],
            [
                'nombre' => 'Celular',
                'marca' => 'Galaxy A36',
                'serie' => 'RFFCY30YGWBD',
                'lugar' => 'Oficina de comunicaciones',
                'estado' => 'En funcionamiento',
                'personal_id' => 7,
                'created_at' => '2026-07-15 11:07:09',
                'updated_at' => '2026-07-15 11:07:09',
            ],
            [
                'nombre' => 'GoPro',
                'marca' => 'Hero',
                'serie' => 'Origen Fac-Medicina',
                'lugar' => 'Oficina de comunicaciones',
                'estado' => 'En funcionamiento',
                'personal_id' => 7,
                'created_at' => '2026-07-15 11:21:38',
                'updated_at' => '2026-07-15 11:30:57',
            ],
            [
                'nombre' => 'Cámara Profesional',
                'marca' => 'SONY',
                'serie' => 'Origen - DINID',
                'lugar' => 'Oficina de comunicaciones',
                'estado' => 'En funcionamiento',
                'personal_id' => 7,
                'created_at' => '2026-07-15 11:25:05',
                'updated_at' => '2026-07-15 11:30:47',
            ],
            [
                'nombre' => 'Cámara',
                'marca' => 'Canon',
                'serie' => 'Donacón - VELT',
                'lugar' => 'Oficina de comunicaciones',
                'estado' => 'En funcionamiento',
                'personal_id' => 7,
                'created_at' => '2026-07-15 11:26:01',
                'updated_at' => '2026-07-15 11:30:42',
            ],
            [
                'nombre' => 'Scanner',
                'marca' => 'EPSON',
                'serie' => 'WFC5790',
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:33:15',
                'updated_at' => '2026-07-15 11:55:33',
            ],
            [
                'nombre' => 'Teclado',
                'marca' => 'RhinoBox',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:33:46',
                'updated_at' => '2026-07-15 11:33:46',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'Teros',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:34:12',
                'updated_at' => '2026-07-15 11:34:12',
            ],
            [
                'nombre' => 'Video Cámara',
                'marca' => 'LOGITECH',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:36:22',
                'updated_at' => '2026-07-15 11:36:39',
            ],
            [
                'nombre' => 'CPU',
                'marca' => 'Rinobox',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:38:14',
                'updated_at' => '2026-07-15 11:38:14',
            ],
            [
                'nombre' => 'Impresora Scanner',
                'marca' => 'Epson',
                'serie' => 'L5590',
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 6,
                'created_at' => '2026-07-15 11:38:56',
                'updated_at' => '2026-07-15 11:40:14',
            ],
            [
                'nombre' => 'Impresora',
                'marca' => 'Lexmar',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:54:48',
                'updated_at' => '2026-07-15 11:54:48',
            ],
            [
                'nombre' => 'Mouse',
                'marca' => 'Rinobox',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:56:07',
                'updated_at' => '2026-07-15 11:56:07',
            ],
            [
                'nombre' => 'Estabilizador',
                'marca' => 'Forza',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 5,
                'created_at' => '2026-07-15 11:56:34',
                'updated_at' => '2026-07-15 11:56:34',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'HP',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 6,
                'created_at' => '2026-07-15 11:56:53',
                'updated_at' => '2026-07-15 11:56:53',
            ],
            [
                'nombre' => 'CPU',
                'marca' => 'Vastec',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 6,
                'created_at' => '2026-07-15 11:57:21',
                'updated_at' => '2026-07-15 11:58:26',
            ],
            [
                'nombre' => 'Teclado',
                'marca' => 'Vastec',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 6,
                'created_at' => '2026-07-15 11:57:41',
                'updated_at' => '2026-07-15 11:57:41',
            ],
            [
                'nombre' => 'Mouse',
                'marca' => 'Vastec',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 6,
                'created_at' => '2026-07-15 11:57:55',
                'updated_at' => '2026-07-15 11:57:55',
            ],
            [
                'nombre' => 'Cámara Web',
                'marca' => 'Logitech',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 6,
                'created_at' => '2026-07-15 11:59:14',
                'updated_at' => '2026-07-15 11:59:14',
            ],
            [
                'nombre' => 'Estabilizador',
                'marca' => 'Forza',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 6,
                'created_at' => '2026-07-15 11:59:30',
                'updated_at' => '2026-07-15 11:59:30',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'HP',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 2,
                'created_at' => '2026-07-15 12:19:02',
                'updated_at' => '2026-07-15 12:19:02',
            ],
            [
                'nombre' => 'cpu',
                'marca' => 'Vastec',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 2,
                'created_at' => '2026-07-15 12:19:57',
                'updated_at' => '2026-07-15 12:19:57',
            ],
            [
                'nombre' => 'Teclado',
                'marca' => 'Vastec',
                'serie' => '740895008993',
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 2,
                'created_at' => '2026-07-15 12:20:42',
                'updated_at' => '2026-07-15 12:20:42',
            ],
            [
                'nombre' => 'Mouse',
                'marca' => 'Vastec',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 2,
                'created_at' => '2026-07-15 12:23:47',
                'updated_at' => '2026-07-15 12:23:47',
            ],
            [
                'nombre' => 'Impresora',
                'marca' => 'HP',
                'serie' => '740841000588',
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 2,
                'created_at' => '2026-07-15 12:24:46',
                'updated_at' => '2026-07-15 12:24:46',
            ],
            [
                'nombre' => 'Estabilizador',
                'marca' => 'Forza',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 2,
                'created_at' => '2026-07-15 12:25:31',
                'updated_at' => '2026-07-15 12:41:52',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 3,
                'created_at' => '2026-07-15 12:26:25',
                'updated_at' => '2026-07-15 12:26:25',
            ],
            [
                'nombre' => 'CPU',
                'marca' => 'Thinkcentre',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 3,
                'created_at' => '2026-07-15 12:26:46',
                'updated_at' => '2026-07-15 12:26:46',
            ],
            [
                'nombre' => 'Teclado',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 3,
                'created_at' => '2026-07-15 12:27:11',
                'updated_at' => '2026-07-15 12:27:11',
            ],
            [
                'nombre' => 'Mouse',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 3,
                'created_at' => '2026-07-15 12:27:26',
                'updated_at' => '2026-07-15 12:27:26',
            ],
            [
                'nombre' => 'Estabilizador',
                'marca' => 'Fes10',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 3,
                'created_at' => '2026-07-15 12:28:29',
                'updated_at' => '2026-07-15 12:28:53',
            ],
            [
                'nombre' => 'Impresora',
                'marca' => 'Epson',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 3,
                'created_at' => '2026-07-15 12:29:54',
                'updated_at' => '2026-07-15 12:29:54',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 4,
                'created_at' => '2026-07-15 12:30:28',
                'updated_at' => '2026-07-15 12:30:28',
            ],
            [
                'nombre' => 'CPU',
                'marca' => 'Thinkcenter',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 4,
                'created_at' => '2026-07-15 12:32:42',
                'updated_at' => '2026-07-15 12:32:42',
            ],
            [
                'nombre' => 'Teclado',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 4,
                'created_at' => '2026-07-15 12:34:20',
                'updated_at' => '2026-07-15 12:34:20',
            ],
            [
                'nombre' => 'Mouse',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 4,
                'created_at' => '2026-07-15 12:34:42',
                'updated_at' => '2026-07-15 12:34:42',
            ],
            [
                'nombre' => 'Estabilizar',
                'marca' => 'Forza',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 4,
                'created_at' => '2026-07-15 12:36:40',
                'updated_at' => '2026-07-15 12:36:40',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'Dell',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:37:42',
                'updated_at' => '2026-07-15 12:37:42',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'Dell',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:38:15',
                'updated_at' => '2026-07-15 12:38:15',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'Teros',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:38:29',
                'updated_at' => '2026-07-15 12:38:29',
            ],
            [
                'nombre' => 'Teclado',
                'marca' => 'Rinobox',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:38:59',
                'updated_at' => '2026-07-15 12:38:59',
            ],
            [
                'nombre' => 'CPU',
                'marca' => 'Rinobox',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:39:33',
                'updated_at' => '2026-07-15 12:39:33',
            ],
            [
                'nombre' => 'Mouse',
                'marca' => 'Rinobox',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:39:44',
                'updated_at' => '2026-07-15 12:39:44',
            ],
            [
                'nombre' => 'Estabilizador',
                'marca' => 'Forza',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:39:57',
                'updated_at' => '2026-07-15 12:42:51',
            ],
            [
                'nombre' => 'Cámara Web',
                'marca' => 'Logitec',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 1,
                'created_at' => '2026-07-15 12:40:13',
                'updated_at' => '2026-07-15 12:40:13',
            ],
            [
                'nombre' => 'Impresora Multifuncional',
                'marca' => 'Edson',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'Guardado',
                'personal_id' => null,
                'created_at' => '2026-07-15 12:43:33',
                'updated_at' => '2026-07-15 12:43:45',
            ],
            [
                'nombre' => 'Monitor',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 8,
                'created_at' => '2026-07-15 12:44:29',
                'updated_at' => '2026-07-15 12:44:29',
            ],
            [
                'nombre' => 'Teclado',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 8,
                'created_at' => '2026-07-15 12:45:13',
                'updated_at' => '2026-07-15 12:45:13',
            ],
            [
                'nombre' => 'Mouse',
                'marca' => 'Lenovo',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 8,
                'created_at' => '2026-07-15 12:45:26',
                'updated_at' => '2026-07-15 12:45:26',
            ],
            [
                'nombre' => 'CPU',
                'marca' => 'Thinkcenter',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 8,
                'created_at' => '2026-07-15 12:45:43',
                'updated_at' => '2026-07-15 12:45:43',
            ],
            [
                'nombre' => 'Estabilizador',
                'marca' => 'Fse10',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => 8,
                'created_at' => '2026-07-15 12:46:09',
                'updated_at' => '2026-07-15 12:46:09',
            ],
            [
                'nombre' => 'Laptop',
                'marca' => 'Dynabook',
                'serie' => null,
                'lugar' => 'Sala de Reuniones',
                'estado' => 'En funcionamiento',
                'personal_id' => 8,
                'created_at' => '2026-07-15 12:48:40',
                'updated_at' => '2026-07-15 13:04:12',
            ],
            [
                'nombre' => 'Televisor',
                'marca' => 'LG',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => null,
                'created_at' => '2026-07-15 13:03:13',
                'updated_at' => '2026-07-15 13:03:13',
            ],
            [
                'nombre' => 'Estabilizador',
                'marca' => 'Elise',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => null,
                'created_at' => '2026-07-15 13:03:57',
                'updated_at' => '2026-07-15 13:03:57',
            ],
            [
                'nombre' => 'Moden',
                'marca' => 'TP-link',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => null,
                'created_at' => '2026-07-15 13:04:34',
                'updated_at' => '2026-07-15 13:04:34',
            ],
            [
                'nombre' => 'Impresora',
                'marca' => 'lexmar',
                'serie' => null,
                'lugar' => 'Oficina principal',
                'estado' => 'En funcionamiento',
                'personal_id' => null,
                'created_at' => '2026-07-15 13:05:21',
                'updated_at' => '2026-07-15 13:05:48',
            ],
        ]);
    }
}